[patch.crates-io]
serial = { git = "https://github.com/bytebeamio/serial-rs", branch = "android_fix" }

[workspace]
members = [
    "disk",
    "protocol",
    "uplink",
]
exclude = [
    "tools/tunshell",
    "tools/utils",
    "tools/simulator",
]

[profile.dev]
opt-level = 1
debug = true
strip = true
panic = "unwind"

[profile.release]
opt-level = "s"
strip = true
panic = "unwind"
