processes = ["echo"]

action_redirections = {}

[tcpapps.1]
port = 5555
actions = []

[persistence]
path = "/tmp/uplink"
max_file_size = 104857600 # 100MB
max_file_count = 3

[simulator]
num_devices = 50
gps_paths = "./paths/"
actions = ["firmware_update", "send_file", "lock", "unlock"]
