processes = []
action_redirections = { "update_firmware" = "install_update" }
persistence_path = "/data/local/tmp/uplink/persistence"

[tcpapps.app]
port = 8031
actions = []

[tcpapps.installer]
port = 8032

[downloader]
actions = [{ name = "update_firmware" }]
path = "/data/local/tmp/uplink/ota"

[ota_installer]
actions = [{ name = "install_update" }]
uplink_port = 8032
path = "/data/local/tmp/uplink/installer"

[streams.device_shadow]
topic = "/tenants/{tenant_id}/devices/{device_id}/events/device_shadow/jsonarray"
buf_size = 128
flush_period = 30

[logging]
tags = ["*"]
min_level = 4

[console]
enabled = true
port = 9328
